name: Epic
description: Group User-Stories under a common issue
title: "[EPIC] <title>"
labels: ["epic"]
body:
  - type: input
    id: persona
    attributes:
      label: As a ...
      description: List the persona this user story applies to.
      placeholder: "Who?"
    validations:
      required: true
  - type: input
    id: accomplishment
    attributes:
      label: I want to ...
      description: What the persona wants to accomplish?
      placeholder: "What?"
    validations:
      required: true
  - type: input
    id: why
    attributes:
      label: So that ...
      description: Why they want to accomplish that thing?
      placeholder: "Why?"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: Metric of Story Progress
      placeholder: |
        * List of requirements at user or system level
        * May also include system flow diagrams or sequence diagrams here.
        * Must be specific to the User Story
        * Must be met to ensure store is complete.
    validations:
      required: false
  - type: textarea
    id: progress
    attributes:
      label: Definition of Done
      description: Metric of Sprint Progress
      placeholder: |
        * List of criteria for ALL User Stories
        * Sprint work only complete once all criteria are met
    validations:
      required: false